// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatRoomProtocol.proto

package optic_fusion1.server.protos;

/**
 * Protobuf type {@code Packet}
 */
public final class Packet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Packet)
    PacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Packet.newBuilder() to construct.
  private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Packet() {
    packetType_ = 0;
    protocolVersion_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Packet();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Packet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            optic_fusion1.server.protos.Packet.PacketType value = optic_fusion1.server.protos.Packet.PacketType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              packetType_ = rawValue;
            }
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            optic_fusion1.server.protos.ProtocolVersion value = optic_fusion1.server.protos.ProtocolVersion.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              protocolVersion_ = rawValue;
            }
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            useEncryption_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return optic_fusion1.server.protos.ChatRoomProtocol.internal_static_Packet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return optic_fusion1.server.protos.ChatRoomProtocol.internal_static_Packet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            optic_fusion1.server.protos.Packet.class, optic_fusion1.server.protos.Packet.Builder.class);
  }

  /**
   * Protobuf enum {@code Packet.PacketType}
   */
  public enum PacketType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HANDSHAKE = 0;</code>
     */
    HANDSHAKE(0),
    ;

    /**
     * <code>HANDSHAKE = 0;</code>
     */
    public static final int HANDSHAKE_VALUE = 0;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PacketType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PacketType forNumber(int value) {
      switch (value) {
        case 0: return HANDSHAKE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PacketType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
            public PacketType findValueByNumber(int number) {
              return PacketType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return optic_fusion1.server.protos.Packet.getDescriptor().getEnumTypes().get(0);
    }

    private static final PacketType[] VALUES = values();

    public static PacketType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PacketType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Packet.PacketType)
  }

  private int bitField0_;
  public static final int PACKET_TYPE_FIELD_NUMBER = 1;
  private int packetType_;
  /**
   * <code>required .Packet.PacketType packet_type = 1;</code>
   * @return Whether the packetType field is set.
   */
  @java.lang.Override public boolean hasPacketType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .Packet.PacketType packet_type = 1;</code>
   * @return The packetType.
   */
  @java.lang.Override public optic_fusion1.server.protos.Packet.PacketType getPacketType() {
    @SuppressWarnings("deprecation")
    optic_fusion1.server.protos.Packet.PacketType result = optic_fusion1.server.protos.Packet.PacketType.valueOf(packetType_);
    return result == null ? optic_fusion1.server.protos.Packet.PacketType.HANDSHAKE : result;
  }

  public static final int PROTOCOL_VERSION_FIELD_NUMBER = 2;
  private int protocolVersion_;
  /**
   * <code>required .ProtocolVersion protocol_version = 2;</code>
   * @return Whether the protocolVersion field is set.
   */
  @java.lang.Override public boolean hasProtocolVersion() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>required .ProtocolVersion protocol_version = 2;</code>
   * @return The protocolVersion.
   */
  @java.lang.Override public optic_fusion1.server.protos.ProtocolVersion getProtocolVersion() {
    @SuppressWarnings("deprecation")
    optic_fusion1.server.protos.ProtocolVersion result = optic_fusion1.server.protos.ProtocolVersion.valueOf(protocolVersion_);
    return result == null ? optic_fusion1.server.protos.ProtocolVersion.VERSION_000 : result;
  }

  public static final int USE_ENCRYPTION_FIELD_NUMBER = 3;
  private boolean useEncryption_;
  /**
   * <code>optional bool use_encryption = 3 [default = false];</code>
   * @return Whether the useEncryption field is set.
   */
  @java.lang.Override
  public boolean hasUseEncryption() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional bool use_encryption = 3 [default = false];</code>
   * @return The useEncryption.
   */
  @java.lang.Override
  public boolean getUseEncryption() {
    return useEncryption_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasPacketType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasProtocolVersion()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, packetType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, protocolVersion_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(3, useEncryption_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, packetType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, protocolVersion_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, useEncryption_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof optic_fusion1.server.protos.Packet)) {
      return super.equals(obj);
    }
    optic_fusion1.server.protos.Packet other = (optic_fusion1.server.protos.Packet) obj;

    if (hasPacketType() != other.hasPacketType()) return false;
    if (hasPacketType()) {
      if (packetType_ != other.packetType_) return false;
    }
    if (hasProtocolVersion() != other.hasProtocolVersion()) return false;
    if (hasProtocolVersion()) {
      if (protocolVersion_ != other.protocolVersion_) return false;
    }
    if (hasUseEncryption() != other.hasUseEncryption()) return false;
    if (hasUseEncryption()) {
      if (getUseEncryption()
          != other.getUseEncryption()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPacketType()) {
      hash = (37 * hash) + PACKET_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + packetType_;
    }
    if (hasProtocolVersion()) {
      hash = (37 * hash) + PROTOCOL_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + protocolVersion_;
    }
    if (hasUseEncryption()) {
      hash = (37 * hash) + USE_ENCRYPTION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUseEncryption());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static optic_fusion1.server.protos.Packet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static optic_fusion1.server.protos.Packet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static optic_fusion1.server.protos.Packet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static optic_fusion1.server.protos.Packet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static optic_fusion1.server.protos.Packet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static optic_fusion1.server.protos.Packet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static optic_fusion1.server.protos.Packet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static optic_fusion1.server.protos.Packet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static optic_fusion1.server.protos.Packet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static optic_fusion1.server.protos.Packet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static optic_fusion1.server.protos.Packet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static optic_fusion1.server.protos.Packet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(optic_fusion1.server.protos.Packet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Packet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Packet)
      optic_fusion1.server.protos.PacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return optic_fusion1.server.protos.ChatRoomProtocol.internal_static_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return optic_fusion1.server.protos.ChatRoomProtocol.internal_static_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              optic_fusion1.server.protos.Packet.class, optic_fusion1.server.protos.Packet.Builder.class);
    }

    // Construct using optic_fusion1.server.protos.Packet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      packetType_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      protocolVersion_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      useEncryption_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return optic_fusion1.server.protos.ChatRoomProtocol.internal_static_Packet_descriptor;
    }

    @java.lang.Override
    public optic_fusion1.server.protos.Packet getDefaultInstanceForType() {
      return optic_fusion1.server.protos.Packet.getDefaultInstance();
    }

    @java.lang.Override
    public optic_fusion1.server.protos.Packet build() {
      optic_fusion1.server.protos.Packet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public optic_fusion1.server.protos.Packet buildPartial() {
      optic_fusion1.server.protos.Packet result = new optic_fusion1.server.protos.Packet(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.packetType_ = packetType_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.protocolVersion_ = protocolVersion_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.useEncryption_ = useEncryption_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof optic_fusion1.server.protos.Packet) {
        return mergeFrom((optic_fusion1.server.protos.Packet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(optic_fusion1.server.protos.Packet other) {
      if (other == optic_fusion1.server.protos.Packet.getDefaultInstance()) return this;
      if (other.hasPacketType()) {
        setPacketType(other.getPacketType());
      }
      if (other.hasProtocolVersion()) {
        setProtocolVersion(other.getProtocolVersion());
      }
      if (other.hasUseEncryption()) {
        setUseEncryption(other.getUseEncryption());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasPacketType()) {
        return false;
      }
      if (!hasProtocolVersion()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      optic_fusion1.server.protos.Packet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (optic_fusion1.server.protos.Packet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int packetType_ = 0;
    /**
     * <code>required .Packet.PacketType packet_type = 1;</code>
     * @return Whether the packetType field is set.
     */
    @java.lang.Override public boolean hasPacketType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .Packet.PacketType packet_type = 1;</code>
     * @return The packetType.
     */
    @java.lang.Override
    public optic_fusion1.server.protos.Packet.PacketType getPacketType() {
      @SuppressWarnings("deprecation")
      optic_fusion1.server.protos.Packet.PacketType result = optic_fusion1.server.protos.Packet.PacketType.valueOf(packetType_);
      return result == null ? optic_fusion1.server.protos.Packet.PacketType.HANDSHAKE : result;
    }
    /**
     * <code>required .Packet.PacketType packet_type = 1;</code>
     * @param value The packetType to set.
     * @return This builder for chaining.
     */
    public Builder setPacketType(optic_fusion1.server.protos.Packet.PacketType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      packetType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .Packet.PacketType packet_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPacketType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      packetType_ = 0;
      onChanged();
      return this;
    }

    private int protocolVersion_ = 0;
    /**
     * <code>required .ProtocolVersion protocol_version = 2;</code>
     * @return Whether the protocolVersion field is set.
     */
    @java.lang.Override public boolean hasProtocolVersion() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .ProtocolVersion protocol_version = 2;</code>
     * @return The protocolVersion.
     */
    @java.lang.Override
    public optic_fusion1.server.protos.ProtocolVersion getProtocolVersion() {
      @SuppressWarnings("deprecation")
      optic_fusion1.server.protos.ProtocolVersion result = optic_fusion1.server.protos.ProtocolVersion.valueOf(protocolVersion_);
      return result == null ? optic_fusion1.server.protos.ProtocolVersion.VERSION_000 : result;
    }
    /**
     * <code>required .ProtocolVersion protocol_version = 2;</code>
     * @param value The protocolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolVersion(optic_fusion1.server.protos.ProtocolVersion value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      protocolVersion_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>required .ProtocolVersion protocol_version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocolVersion() {
      bitField0_ = (bitField0_ & ~0x00000002);
      protocolVersion_ = 0;
      onChanged();
      return this;
    }

    private boolean useEncryption_ ;
    /**
     * <code>optional bool use_encryption = 3 [default = false];</code>
     * @return Whether the useEncryption field is set.
     */
    @java.lang.Override
    public boolean hasUseEncryption() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bool use_encryption = 3 [default = false];</code>
     * @return The useEncryption.
     */
    @java.lang.Override
    public boolean getUseEncryption() {
      return useEncryption_;
    }
    /**
     * <code>optional bool use_encryption = 3 [default = false];</code>
     * @param value The useEncryption to set.
     * @return This builder for chaining.
     */
    public Builder setUseEncryption(boolean value) {
      bitField0_ |= 0x00000004;
      useEncryption_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool use_encryption = 3 [default = false];</code>
     * @return This builder for chaining.
     */
    public Builder clearUseEncryption() {
      bitField0_ = (bitField0_ & ~0x00000004);
      useEncryption_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Packet)
  }

  // @@protoc_insertion_point(class_scope:Packet)
  private static final optic_fusion1.server.protos.Packet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new optic_fusion1.server.protos.Packet();
  }

  public static optic_fusion1.server.protos.Packet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Packet>
      PARSER = new com.google.protobuf.AbstractParser<Packet>() {
    @java.lang.Override
    public Packet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Packet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Packet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Packet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public optic_fusion1.server.protos.Packet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

